src/Exa/ProdeBundle/Form/Type/ApuestaFormType.php
<?php

namespace Exa\ProdeBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\Form\FormInterface;

class ApuestaFormType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //$builder->add('partido', new PartidoFormType() );
        $builder->add('prediccion', 'choice', array(
            'choices' => array("L" => "local", "E" => "Empate", "V" => "Visitante"),
            'expanded' => true,
            'multiple' => false
        ));
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver);
        $resolver->setDefaults(array(
            'data_class' => 'Exa\ProdeBundle\Entity\Apuesta',
        ));
    }
    
    public function buildView(FormView $view, FormInterface $form, array $options) {
        parent::buildView($view, $form, $options);
    }

    public function getName()
    {
        return 'apuesta';
    }
    
    public function getParent() {
        return 'form';
    }
    
}

?>

src/Exa/ProdeBundle/Controller/DefaultController.php
<?php

namespace Exa\ProdeBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Exa\ProdeBundle\Form\Type\TarjetaApuestasFormType;
use Exa\ProdeBundle\Entity\Partido;

use Hip\MandrillBundle\Message;
use Hip\MandrillBundle\Dispatcher;

class DefaultController extends Controller
{
    public function indexAction()
    {   
        $usuario = $this->getUser();
        $fecha = $this->getDoctrine()->getRepository("ExaProdeBundle:Fecha")->getFechaForLiga($usuario->getEquipo()->getLiga());
        $tarjetaApuestas = $this->get('tarjeta_apuestas_usuario')->getPreparedTarjetaApuesta($usuario, $fecha);
        $form = $this->createForm(new TarjetaApuestasFormType(), $tarjetaApuestas);
        // guardar los cambios si la request viene del POST
        if ($this->getRequest()->isMethod('POST')) {
            $form->bind($this->getRequest());
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($tarjetaApuestas);
                $em->flush();
                $this->get('session')->getFlashBag()->add('success', 'Su apuesta fue enviada correctamente! Recuerde que tiene tiempo de modificarla hasta que empiece la veda');

            } else $this->get('session')->getFlashBag()->add('error', 'Error al enviar su apuesta! Intentelo nuevamente.');
        }
        // mostrar el formulario
        return $this->render('ExaProdeBundle:Default:home.html.twig', array("form" => $form->createView() , 'fecha' => $fecha));
    }
    
    public function userPositionsAction() {
        $usuario = $this->getUser();
        $fecha = $this->getDoctrine()->getRepository("ExaProdeBundle:Fecha")->getFechaForLiga($usuario->getEquipo()->getLiga(), false);
        $posicion = $this->get('posiciones_usuario')->getPosicionUsuario($usuario, $fecha);
        $posicion_torneo = empty($fecha) ? null : $this->get('posiciones_usuario')->getPosicionUsuario($usuario, null, $fecha->getLiga());
        return $this->render(
                'ExaProdeBundle:Default:posiciones_usuario.html.twig',
                array('posicion_fecha' => $posicion, 'posicion_torneo' => $posicion_torneo,  'fecha' => $fecha)
                
            );
    }
    
    public function apuestasAnterioresAction() {
        $usuario = $this->getUser();
        $apuestas = $this->getDoctrine()->getRepository('ExaProdeBundle:TarjetaApuestas')->getPastTarjetasUsuario($usuario);
        return $this->render(
                'ExaProdeBundle:Default:apuestas_anteriores.html.twig',
                array('Tapuestas' => $apuestas)
        );
    }
    
    public function rankingAction($type) {
        $posiciones = $this->get('posiciones_usuario')->getPosicionesParaTodasLigas($type);
        $template = $type == "fecha" ? "ExaProdeBundle:Default:ranking_jugadores.html.twig" :
            "ExaProdeBundle:Default:ranking_jugadores_torneo.html.twig";
        return $this->render(
                $template,
                array('tipo' => $type, 'posiciones' => $posiciones)
        );
    }
    
    public function porcentajePrediccionAction($partido, $prediccion) {
        $porc = $this->getDoctrine()->getRepository('ExaProdeBundle:Apuesta')->getPorcentajePrediccion($partido, $prediccion);
        return $this->render('ExaProdeBundle:Default:apuesta_porcentaje.html.twig', 
                array('porcentaje' =>  sprintf("%s%%", $porc * 100), 'prediccion' => $prediccion)
        );
    }
    
}

src/Exa/ProdeBundle/Resources/views/Default/apuesta_porcentaje.html.twig
<span class="prode-porcentaje-apuesta {% if prediccion == "E" %}prode-porcentaje-abajo{% endif %}">{{ porcentaje }} <i class='icon-question-sign' data-placement='right' data-toggle="tooltip" title="Éste porcentaje es calculado por el sistema de acuerdo a los usuarios que apostaron por ésta opción, y el mismo irá variando a medida que más usuarios hagan o cambien sus apuestas"></i></span>

src/Exa/ProdeBundle/Resources/views/Default/apuestas_anteriores.html.twig
{# empty Twig template #}
{% extends 'ExaProdeBundle:Default:authenticated.html.twig' %}
{% block pagecontent %}
<h3>Apuesta terminadas</h3>
<hr>
{% if Tapuestas is not null %}
{% for Tapuesta in Tapuestas %}
<table class="table table-bordered table-striped">
    <thead>
        <tr class="prode-tarjeta-header">
            <td colspan="2" class="prode-tarjeta-right">{{ Tapuesta.fecha }}</td>
        </tr>
        <tr>
            <td><strong>Partido</stron></td>
            <td class="prode-tarjeta-centered"><strong>Predicción</strong></td>
        </tr>
    </thead>
    <tbody>
        {% for apuesta in Tapuesta.apuestas %}
        <tr>
            <td>{{ apuesta.partido }}</td>
            <td class="prode-tarjeta-centered {% if apuesta.acertoResultado %}prode-acierto{% else %}prode-sin-acierto{% endif %}" >{{ apuesta.prediccion }}</td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="2" class="prode-tarjeta-right">Total aciertos: {{ Tapuesta.aciertos }}</td>
        </tr>
    </tfoot>
</table>
<hr>
{% endfor%}
{% else %}
<p>El usuario no tiene apuestas anteriores</p>
{% endif %}

{% endblock %}

src/Exa/ProdeBundle/Resources/views/Default/authenticated.html.twig
{% extends '::base.html.twig' %}

{% block title %} {{ parent() }} - Bienvenido {{app.user.name}}! {% endblock %}

{% block userinfo %} 
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i> {{ app.user.nameteam }}  <b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li><a href="{{ path('fos_user_profile_show') }}"><i class="icon-pencil"></i> Mi Usuario</a></li>
        <li><a href="{{ path('apuestas_anteriores')}}"><i class="icon-list-alt"></i> Mis apuestas</a></li>
        {% if is_granted('ROLE_ADMIN') %}
        <li class="divider"></li>
        <li><a href="{{ path('sonata_admin_dashboard') }}"><i class="icon-eye-open"></i> Administrar el sitio</a></li>
        {% endif %}
        {% if is_granted('ROLE_PREVIOUS_ADMIN') %}
        <li class="divider"></li>
        <li><a href="{{ path('exa_prode_homepage', {_switch_user: '_exit'}) }}">Exit impersonation</a></li>
        {% endif %}
        <li class="divider"></li>
        <li><a href="{{ path('fos_user_security_logout') }}"><i class="icon-off"></i> Cerrar sesion</a></li>
    </ul>
</li>
{% endblock %}

{% block content %}

<div class="span3 bs-docs-sidebar">
    <ul class="nav nav-tabs nav-stacked">
      <li><a href="{{ path('exa_prode_homepage') }}"><i class="icon-chevron-right"></i> Tarjeta de Apuestas Actual</a></li>
      <li><a href="{{ path('apuestas_anteriores') }}"><i class="icon-chevron-right"></i> Apuestas anteriores</a></li>
      <li><a href="{{ path('ranking_jugadores', {'type': 'fecha'}) }}"><i class="icon-chevron-right"></i> Ranking por fecha</a></li>
      <li><a href="{{ path('ranking_jugadores', {'type': 'torneo'}) }}"><i class="icon-chevron-right"></i> Ranking por torneo</a></li>      
    </ul>
</div>
<div class="span6">
    {% block pagecontent %}{% endblock %}
</div>
<div class="span3 award">
   {{ render(controller('ExaProdeBundle:Default:userPositions')) }}
</div>

{% endblock %}

src/Exa/ProdeBundle/Resources/views/Default/home.html.twig
{# empty Twig template #}
{% extends 'ExaProdeBundle:Default:authenticated.html.twig' %}
{% form_theme form 'ExaProdeBundle:Form:fields_apuestas.html.twig' %}
{% block pagecontent %}
<h3>Tarjeta de apuestas actual</h3>
{% if fecha is not null %}
<h4>{{ fecha }}</h4>

<p class="prode-veda">Veda: {{ fecha.veda|date('d-m-Y') }} a las 0:00 hs.</p>

<form action="{{path("exa_prode_homepage") }}" method="POST" {{ form_enctype(form) }}>
    {# render the task's only field: description #}
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th class="prode-tarjeta-header" colspan="5">APUESTAS</th>
            </tr>
            <tr>
                <th colspan="2">Equipo Local</th>
                <th class="prode-tarjeta-centered">Empate</th>
                <th class="prode-tarjeta-right" colspan="2">Equipo Visitante</th>
            </tr>
        </thead>
        <tbody>
            {% for apuesta in form.apuestas %}
                {{ form_widget(apuesta) }}
            {% endfor %}
        </tbody>
    </table>
        {{ form_rest(form) }}
        <div class="form-actions">
            <input type="submit" value="Enviar Apuesta" class="btn btn-success pull-right" />
        </div>
</form>
{% else %}
<h4>Por el momento, no hay apuestas vigentes.</h4>
{% endif %}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(document).ready(function(){
            $('.icon-question-sign').tooltip();
        });
    </script>
{% endblock %}

src/Exa/ProdeBundle/Resources/views/Default/posiciones_usuario.html.twig
{# empty Twig template #}
<div class="prode-posiciones-usuario">
    <h4>Resultados última fecha</h4>
    {% if fecha is not null %}
    <h5>{{ fecha.name }} - {{fecha.liga.shortname }}</h5>
    {% if posicion_fecha.aciertos > 0 %}
    <p class="posicion"><span>{{ posicion_fecha.posicion }}º</span>en la {{fecha.name}}, con <strong>{{posicion_fecha.aciertos}} aciertos.</strong></p>
    {% else %}
    <p>{{ posicion_fecha.posicion }}</p>
    {% endif %}
    <p class="posicion"><span>{{ posicion_torneo.posicion }}º</span> en el torneo {{fecha.liga.shortname}}, con <strong>{{posicion_torneo.aciertos}} aciertos en total.</strong></p>
    {% else %}
    <p>El usuario no ha apostado todavía.</p>
    {% endif %}
</div>

src/Exa/ProdeBundle/Resources/views/Default/ranking_jugadores.html.twig
{# empty Twig template #}
{% extends 'ExaProdeBundle:Default:authenticated.html.twig' %}
{% block pagecontent %}
<h3>Posiciones en {{ tipo }}</h3>
  <ul class="nav nav-tabs">
    {% for key,posiciones_liga in posiciones %}
        {% if posiciones_liga is not null %}
        <li><a href="#tab{{key}}" data-toggle="tab">{{ posiciones_liga[0].fecha.liga.getshortname }}</a></li>
        {% endif %}
    {% endfor %}
  </ul>
  <div class="tab-content">
    {% for key,posiciones_liga in posiciones %}
        {% if posiciones_liga is not null %}
        <div class="tab-pane fade" id="tab{{key}}">
            {% if tipo == "fecha" %}
                <p class="prode-tarjeta-right">{{ posiciones_liga[0].fecha.name }}</p>
            {% endif %}
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th class="prode-tarjeta-centered">Usuario</th>
                        <th class="prode-tarjeta-centered">Equipo</th>
                        <th class="prode-tarjeta-centered">Aciertos</th>
                    </tr>
                </thead>
                <tbody>
                    {% for k,posicion in posiciones_liga %}
                    <tr>
                        <td>{{k + 1}}</td>
                        <td>{{posicion.usuario.name}} ({{ posicion.usuario }})</td>
                        <td>{{ posicion.usuario.equipo.name}}</td>
                        <td>{{posicion.aciertos}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    {% endfor %}
  </div>
{% endblock %}

src/Exa/ProdeBundle/Resources/views/Default/ranking_jugadores_torneo.html.twig
{# empty Twig template #}
{% extends 'ExaProdeBundle:Default:authenticated.html.twig' %}
{% block pagecontent %}
<h3>Posiciones en {{ tipo }}</h3>
  <ul class="nav nav-tabs">
    {% for key,posiciones_liga in posiciones %}
        {% if posiciones_liga[0][0].fecha is defined %}
        <li><a href="#tab{{key}}" data-toggle="tab">{{ posiciones_liga[0][0].fecha.liga.shortname }}</a></li>
        {% endif %}
    {% endfor %}
  </ul>
  <div class="tab-content">
    {% for key,posiciones_liga in posiciones %}
        {% if posiciones_liga[0][0].fecha is defined %}
        <div class="tab-pane fade" id="tab{{key}}">
            <p class="prode-tarjeta-right">Ranking general del torneo</p>
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th class="prode-tarjeta-centered">Usuario</th>
                        <th class="prode-tarjeta-centered">Equipo</th>
                        <th class="prode-tarjeta-centered">Tot. Aciertos</th>
                    </tr>
                </thead>
                <tbody>
                    {% for k,posicion in posiciones_liga %}
                    <tr>
                        <td>{{k + 1}}</td>
                        <td>{{posicion[0].usuario.name}} ({{ posicion[0].usuario }})</td>
                        <td>{{ posicion[0].usuario.equipo.name}}</td>
                        <td class="prode-tarjeta-centered">{{posicion.total}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    {% endfor %}
  </div>
{% endblock %}